CREATE ROLE postlightuser LOGIN
  PASSWORD 'postlightuser'
  NOSUPERUSER
  INHERIT
  CREATEDB
  NOCREATEROLE
  NOREPLICATION
  VALID UNTIL '2028-03-09 00:00:00'
;

grant postlightuser to postgres;
set role postlightuser;

CREATE DATABASE postlightdb WITH
OWNER = postlightuser
ENCODING = 'UTF8'
LC_COLLATE = 'en_US.UTF-8'
LC_CTYPE = 'en_US.UTF-8'
CONNECTION LIMIT = -1
template template0;

GRANT ALL ON DATABASE postlightdb TO postgres;
GRANT ALL ON DATABASE postlightdb TO public;

ALTER DEFAULT PRIVILEGES
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO public;

ALTER DEFAULT PRIVILEGES
GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO postgres;
